name: CI-CD-Kubernetes
on:
  push:
    branches:
      - main
permissions:
  contents: write
env:
  IMAGE_NAME: my-python-k8s-app
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/${IMAGE_NAME}:${IMAGE_TAG} .
    
    - name: Scan image with Trivy(critical only)
      uses: aquasecurity/trivy-action@0.20.0
      with:
        image-ref: ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
        format: table
        severity: CRITICAL
        exit-code: 1
        
    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/${IMAGE_NAME}:${IMAGE_TAG}



    # stronly recommended to enable image scanning in CI/CD pipeline  
    # - name: Scan image with Trivy
    #   uses: aquasecurity/trivy-action@0.20.0
    #   with:
    #     image-ref: ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
    #     format: json
    #     output: trivy-report.json
    #     exit-code: 0
    # - name: Upload Trivy report
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: trivy-report
    #     path: trivy-report.json